version: '3'
services:
  tartaros:
    image: flask-iris:1.0
    container_name: iris
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/var/log/app
      - ./configs:/etc/app
      - ./model:/model
#    env_file:
#      - .env
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.025'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 1m
      timeout: 3s
      retries: 3
